#!/bin/bash

flask shell

from app import db
from models import User
admin = User(username='admin', email='admin@example.com', is_admin=True)
admin.set_password('admin_password')
db.session.add(admin)
db.session.commit()
